version: "3.2"

services:
  postgres:
    image: postgres:11.10
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin
  minio:
    image: minio/minio:RELEASE.2022-05-08T23-50-31Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - /data
  minio-configurator:
    image: minio/mc:RELEASE.2022-05-09T04-08-26Z
    depends_on:
      minio:
        condition: service_healthy
    environment:
      USER_NAME: test
      USER_PASSWORD: test12345
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000  minio minio123;
      mc mb minio/$$USER_NAME;

      echo \"
      {
        \\\"Version\\\": \\\"2012-10-17\\\",
        \\\"Statement\\\": [
          {
            \\\"Effect\\\": \\\"Allow\\\",
            \\\"Action\\\": [
              \\\"s3:GetBucketLocation\\\",
              \\\"s3:ListAllMyBuckets\\\",
              \\\"s3:ListBucketMultipartUploads\\\"
            ],
            \\\"Resource\\\": [\\\"arn:aws:s3:::$$USER_NAME\\\"]
          },
          {
            \\\"Effect\\\": \\\"Allow\\\",
            \\\"Action\\\": [
              \\\"s3:GetObject\\\",
              \\\"s3:AbortMultipartUpload\\\",
              \\\"s3:ListMultipartUploadParts\\\",
              \\\"s3:ListBucket\\\",
              \\\"s3:PutObject\\\",
              \\\"s3:DeleteObject\\\"
            ],
            \\\"Resource\\\": [\\\"arn:aws:s3:::$$USER_NAME/*\\\"]
          }
        ]
      }
      \" > /tmp/policy.json;
      mc admin user add minio $$USER_NAME $$USER_PASSWORD;
      mc admin policy add minio $$USER_NAME /tmp/policy.json;
      mc admin policy set minio $$USER_NAME user=$$USER_NAME;
      "