version: "3.2"

services:
  postgres:
    image: postgres:11.10
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=admin